### ISSUE TITLE
Sign in with Orcid button doesn't take me to a sign-in page

### ISSUE THREAD

**Issue by sfbetz** [ualbertalib/lagotto#2]
It's very possible I'm missing something but on first try, clicking the login with Orcid button:
![2016-04-19_16-54-42](https://cloud.githubusercontent.com/assets/12801010/14658261/acb60f28-064f-11e6-8142-89d6d266839b.png)

... doesn't take me to expected login screen. Instead it displays an "Error signing in with Orcid" message:

![2016-04-19_16-55-06](https://cloud.githubusercontent.com/assets/12801010/14658277/cbd511ec-064f-11e6-96ee-3d125885274c.png)

**Comment by pbinkley** [comment]
Note that the "Sign in with ORCID" link points to ```/users/auth/orcid```, but you end up back at ```/``` with the error message.
